version: '3'

services:
  locust:
    image: locustio/locust
    ports:
     - "8089:8089"
    volumes:
      - ./:/org/thoughtworks
    command: -f /Users/aman.sharma/Desktop/Docs/locust-starter/org/thoughtworks/locust_load.py
#    command: -f /mnt/locust/locustfile.py --master -H http://master:8089
#
#  worker:
#    image: locustio/locust
#    volumes:
#      - ./:/mnt/locust
#    command: -f /mnt/locust/locustfile.py --worker --master-host master