version: '3'

services:
  master:
    build: .
    ports:
      - 8089:8089
    command: -f ${filename} --master --headless --expect-workers ${numberofworkers} -H ${host} --scenario=${scenario}
  worker:
    build: .
    ports:
      - "6000-6500:6501"
    command: -f ${filename} --worker --master-host master
